" varying vec4 diffuse;                                                                                 \n"
" varying vec4 ambientGlobal;                                                                                  \n"
" varying vec4 ambient;                                                                                 \n"
"                                                                                  \n"
" varying vec4 specular;                                                                                 \n"
"                                                                                  \n"
" varying vec3 normal;                                                                                 \n"
" varying vec3 lightDir;                                                                                 \n"
"                                                                                  \n"
"                                                                                  \n"
" varying float dist;                                                                                 \n"
"                                                                                  \n"
" varying vec4 alphaSpecular;                                                                                 \n"
" 	                                                                                 \n"
" 	                                                                                 \n"
" void main()                                                                                      \n"
" {                                                                                                \n"
" 	vec3 n;                                                                                        \n"
" 	vec3 halfV;                                                                                    \n"
" 	vec3 viewV;                                                                                    \n"
" 	vec3 ldir;                                                                                     \n"
" 	                                                                                               \n"
"     float NdotL;                                                                                 \n"
"                                                                                                  \n"
"     vec4 color = ambientGlobal;                                                                  \n"
" 	float att;                                                                                     \n"

" 	n = normalize(normal);                                                                         \n"
" 	NdotL = max(dot(n,lightDir),0.0);                                                              \n"

"     att = 1.0 / (gl_LightSource[0].quadraticAttenuation);                                        \n"

"     color += att * (diffuse * NdotL + ambient);                                                  \n"
"     color +=  att * vec4(-9.60, 0.0, 9.60, 1.0) * pow(NdotL, 45.2);                              \n"
"     gl_FragColor = color* NdotL;                                                                 \n"

" }                                                                                 \n"
"                                                                                  \n"
"                                                                                  \n"
"                                                                                  \n"
"                                                                                  \n"
" ///////////////////////////////////////////////////////////////////////////////////////////////////                                                                                 \n"
" ///////////////////////////////////////////////////////////////////////////////////////////////////	                                                                                       \n"
" ///////////////////////////////////////////////////////////////////////////////////////////////////                                                                                 \n"
" ///////////////////////////////////////////////////////////////////////////////////////////////////                                                                                 \n"
" ///////////////////////////////////////////////////////////////////////////////////////////////////                                                                                 \n"
"                                                                                  \n"
"                                                                                  \n"
"                                                                                  \n"
" /*//_____FROSTY_SHADER_____FROSTY_SHADER_____FROSTY_SHADER_____FROSTY_SHADER_____FROSTY_SHADER                                                                                 \n"
"                                                                                  \n"
" varying vec4 diffuse;                                                                                 \n"
" varying vec4 ambientGlobal;                                                                                  \n"
" varying vec4 ambient;                                                                                 \n"
"                                                                                  \n"
" varying vec4 specular;                                                                                 \n"
"                                                                                  \n"
" varying vec3 normal;                                                                                 \n"
" varying vec3 lightDir;                                                                                 \n"
" varying vec3 halfVector;                                                                                 \n"
"                                                                                  \n"
" varying float dist;                                                                                 \n"
"                                                                                  \n"
" varying vec4 alphaSpecular;                                                                                 \n"
" 	                                                                                 \n"
" 	                                                                                 \n"
" void main()                                                                                 \n"
" {                                                                                 \n"
" 	vec3 n;                                                                                 \n"
" 	vec3 halfV;                                                                                 \n"
" 	vec3 viewV;                                                                                 \n"
" 	vec3 ldir;                                                                                 \n"
" 	                                                                                 \n"
"     float NdotL;                                                                                 \n"
"     float NdotHV;                                                                                 \n"
"                                                                                  \n"
"     vec4 color = ambientGlobal;                                                                                 \n"
" 	float att;                                                                                 \n"
" 		                                                                                 \n"
" 	n = normalize(normal);                                                                                 \n"
" 	NdotL = max(dot(n,normalize(lightDir)),0.0);                                                                                 \n"
"                                                                                  \n"
"     att = 1.0 / (gl_LightSource[0].quadraticAttenuation);                                                                                 \n"
" 			                                                                                 \n"
"     color += att * (diffuse * NdotL + ambient);                                                                                 \n"
" 		                                                                                 \n"
"     halfV = normalize(halfVector);                                                                                 \n"
"     NdotHV = max(dot(n,halfV),0.0);                                                                                 \n"
"                                                                                      \n"
"     color +=  att * vec4(-9.60, 0.0, 9.60, 1.0) * pow(NdotL, 12.2);                                                                                 \n"
" 		                                                                                 \n"
"     gl_FragColor = color* NdotL;                                                                                 \n"
" }                                                                                 \n"
"                                                                                  \n"
"                                                                                  \n"
" }*/                                                                                 \n"
